# Generated by Django 5.0.6 on 2025-05-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴 이름')),
                ('description', models.TextField(verbose_name='메뉴 설명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('total_servings', models.IntegerField(verbose_name='총 준비 수량')),
                ('sold_servings', models.IntegerField(default=0, verbose_name='판매된 수량')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='메뉴 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴',
            },
        ),
    ]
